#pragma once
// Factory presets (generated by tools/gen_presets.py into factory.inc). Each one is a text snippet in the state
// format (see State/State.h) with p.* global keys and all.* / row<R>.* clip keys; loading it keeps the samples.
namespace cp
{
struct FactoryPreset { const char* category; const char* name; const char* text; };
inline const FactoryPreset* factoryPresets (int& count)
{
    static const FactoryPreset k[] {
#include "factory.inc"
    };
    count = (int) (sizeof k / sizeof k[0]);
    return k;
}
// "Category: Name" labels for the preset selector
inline const char* const* factoryPresetLabels (int& count)
{
    static char labels[128][64];
    static const char* ptr[128];
    const FactoryPreset* p = factoryPresets (count);
    if (count > 128) count = 128;
    for (int i = 0; i < count; ++i) { std::snprintf (labels[i], sizeof labels[i], "%s: %s", p[i].category, p[i].name); ptr[i] = labels[i]; }
    return ptr;
}
} // namespace cp
