#!/usr/bin/env python3
"""Pre-render the MPC Arcade UI fonts into src/frontend/font_data.h (8-bit coverage atlases, no font library needed
on the MPC). Text: Titillium Web (the MPC's own UI typeface, SIL OFL, third_party/). Symbols: DejaVu Sans Bold.
Usage: python3 tools/make_font.py     (needs Pillow)"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TP = os.path.join(ROOT, "third_party")
SYMFONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
# id, file, pixel size   (ids must match enum FontId in gfx.h)
FONTS = [("F_SMALL", "TitilliumWeb-SemiBold.ttf", 18), ("F_BODY", "TitilliumWeb-SemiBold.ttf", 22),
         ("F_BOLD", "TitilliumWeb-Bold.ttf", 24), ("F_TITLE", "TitilliumWeb-Bold.ttf", 32),
         ("F_HUGE", "TitilliumWeb-Bold.ttf", 46)]
SYMBOLS = "★☆▲▼◀▶✓✕•⌫↻⚙♪⏸●○·…→←↑↓"
CHARS = [chr(c) for c in range(32, 127)] + [chr(c) for c in range(0xA0, 0x100)] + list(SYMBOLS)

out = ["// Generated by tools/make_font.py - do not edit.", "#pragma once", "#include <stdint.h>",
       "typedef struct { uint32_t cp; uint16_t x, y; uint8_t w, h; int8_t ox, oy; uint8_t adv; } Glyph;",
       "typedef struct { int size, ascent, height, nglyphs, aw, ah; const Glyph* g; const uint8_t* atlas; } FontData;"]
tables = []
for fid, fname, size in FONTS:
    f = ImageFont.truetype(os.path.join(TP, fname), size)
    sym = ImageFont.truetype(SYMFONT, int(size * 0.82))
    ascent, descent = f.getmetrics()
    glyphs, ims = [], []
    for ch in CHARS:
        ff = sym if ch in SYMBOLS else f
        bbox = ff.getbbox(ch)
        adv = int(round(ff.getlength(ch)))
        if ch in SYMBOLS: adv = max(adv, int(size * 0.62))
        if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append((ord(ch), 0, 0, 0, 0, 0, 0, adv)); ims.append(None); continue
        w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
        im = Image.new("L", (w, h), 0)
        dy = 0
        if ch in SYMBOLS:                                   # centre symbols on the text's x-height band
            sa, sd = sym.getmetrics(); dy = (ascent - sa) // 2 + int(size * 0.04)
        ImageDraw.Draw(im).text((-bbox[0], -bbox[1]), ch, font=ff, fill=255)
        glyphs.append([ord(ch), 0, 0, w, h, bbox[0], bbox[1] + dy, adv]); ims.append(im)
    # shelf-pack into a 512-wide atlas
    AW, x, y, rowh = 512, 0, 0, 0
    for g, im in zip(glyphs, ims):
        if im is None: continue
        if x + im.width > AW: x, y, rowh = 0, y + rowh + 1, 0
        g[1], g[2] = x, y; x += im.width + 1; rowh = max(rowh, im.height)
    AH = y + rowh + 1
    atlas = Image.new("L", (AW, AH), 0)
    for g, im in zip(glyphs, ims):
        if im is not None: atlas.paste(im, (g[1], g[2]))
    data = atlas.tobytes()
    name = fid.lower()
    out.append(f"static const uint8_t {name}_atlas[{len(data)}] = {{")
    for i in range(0, len(data), 40): out.append(",".join(str(b) for b in data[i:i + 40]) + ",")
    out.append("};")
    out.append(f"static const Glyph {name}_glyphs[{len(glyphs)}] = {{")
    for g in glyphs: out.append("{%d,%d,%d,%d,%d,%d,%d,%d}," % tuple(g))
    out.append("};")
    tables.append(f"{{{size},{ascent},{ascent + descent},{len(glyphs)},{AW},{AH},{name}_glyphs,{name}_atlas}}")
out.append("static const FontData kFonts[] = {" + ",".join(tables) + "};")
dst = os.path.join(ROOT, "src", "frontend", "font_data.h")
open(dst, "w").write("\n".join(out) + "\n")
print("wrote", dst, os.path.getsize(dst) // 1024, "KB")
