# gglue_prepare_vst2_sdk(<sdk dir> <out var>)
# Steinberg VST2 SDK: used as is. FST header: copied into the build folder with VstSpeakerArrangement::speakers
# declared as speakers[8] (the Steinberg ABI layout: 8 + 8 * 112 = 904 bytes), which is what JUCE's VST2 wrapper and
# host code assume when they allocate speaker arrangements. Nothing is vendored into the repository.
function(gglue_prepare_vst2_sdk sdk out)
    set(fst "${sdk}/pluginterfaces/vst2.x/fst.h")
    if(NOT EXISTS "${fst}")
        set(fst "${sdk}/pluginterfaces/fst/fst.h")
    endif()
    if(NOT EXISTS "${fst}")
        if(NOT EXISTS "${sdk}/pluginterfaces/vst2.x/aeffect.h")
            message(FATAL_ERROR "GGLUE_VST2_SDK_DIR=${sdk} has no pluginterfaces/vst2.x/aeffect.h")
        endif()
        message(STATUS "G-Glue VST2: Steinberg VST2 SDK at ${sdk}")
        set(${out} "${sdk}" PARENT_SCOPE)
        return()
    endif()
    file(READ "${fst}" text)
    string(REPLACE "t_fstSpeakerProperties speakers[];" "t_fstSpeakerProperties speakers[8];" patched "${text}")
    if(patched STREQUAL text AND NOT text MATCHES "speakers\\[8\\]")
        message(FATAL_ERROR "G-Glue VST2: unknown FST version (speakers[] declaration not found in ${fst})")
    endif()
    set(dst "${CMAKE_BINARY_DIR}/vst2-sdk-fst/pluginterfaces/vst2.x")
    file(MAKE_DIRECTORY "${dst}")
    file(WRITE "${dst}/fst.h" "${patched}")
    file(WRITE "${dst}/aeffect.h" "#pragma once\n#define FST2VST 1\n#include \"fst.h\"\n")
    file(WRITE "${dst}/aeffectx.h" "#pragma once\n#define FST2VST 1\n#include \"fst.h\"\n")
    message(STATUS "G-Glue VST2: FST header (${fst}), speaker arrangement patched to the Steinberg layout")
    set(${out} "${CMAKE_BINARY_DIR}/vst2-sdk-fst" PARENT_SCOPE)
endfunction()
