#pragma once
// SSMModel: the SSM2044 4-pole voltage-controlled low-pass on SP-1200 outputs 1-2 (one channel).
//
// What is documented:
//   - outputs 1 and 2 are filtered by SSM2044s; the cutoff follows a simple AR envelope generated by the Z80: open on
//     a hit, then closing (owners report it is near ~250 Hz about a millisecond or so after the hit); a trimmer per
//     filter sets the cutoff; there is no resonance on the outputs (fixed feedback)
//   - the SSM2044 is an "improved ladder" of transconductance cells (Rossum); its successor SSI2144, built on the same
//     internal circuit, specifies a differential input of nominally +-20 mV that clips at +-50 mV, and notes better
//     control feedthrough than the original (i.e. the SSM2044 has noticeable control feedthrough)
// The model:
//   - four one-pole cells, each dy/dt = wc * (T(x) - T(y)) with T = tanh of the cell's differential voltage
//     (bipolar transconductor), solved semi-implicitly per sample (zero-delay, linearised around the current state),
//     run 1x / 2x / 4x oversampled by the quality setting
//   - input level: converter full scale arrives at the chip as +-10 mV at SSM CHARACTER 0 dB (assumed attenuator,
//     calibrated so the output stays near the SP's published 0.05 % THD at normal levels; +-20 mV nominal / +-50 mV
//     clip from the SSI2144 sheet set the scale of the tanh); SSM CHARACTER moves that level, so hot signals saturate
//     the cells and, with an input offset (COMPONENT VARIATION), add even harmonics; the result depends on level,
//     frequency (cells saturate more where the signal is not yet filtered) and transients
//   - resonance: fixed low feedback (hardware: none; SSM RESONANCE adds it, non-hardware)
//   - control feedthrough: a fraction of the cutoff CV's fast changes leaks to the output (a soft "thump" on hits);
//     its size is not published: set to a subtle -45 dBFS per opened octave, scaled by variation (behavioural)
#include "Dsp.h"

namespace sp
{
struct SSMModel
{
    double fs = 44100.0;                // host rate
    int os = 1;
    float s[4] {};                      // cell states (normalised)
    float y4 = 0.f;
    float g = 0.1f;                     // per-cell coefficient at the oversampled rate
    float level = 0.193f;               // signal scale into the cells: x * level = (volts / 2 Vt)
    float offset = 0.f;                 // input offset in the same units
    float res = 0.f;                    // feedback 0..~3.5
    float amount = 1.f;                 // ANALOG: 0 = linear cells
    float feed = 0.f, cvLp = 0.f, cvLpA = 0.f;
    Halfband up1, up2, dn1, dn2;
    void prepare (double rate, int oversample)
    {
        fs = rate; os = oversample; reset();
        cvLpA = (float) std::exp (-2.0 * kPi * 30.0 / fs);
    }
    void reset() { s[0] = s[1] = s[2] = s[3] = 0.f; y4 = 0.f; up1.reset(); up2.reset(); dn1.reset(); dn2.reset(); cvLp = -1.f; }
    void setCutoff (float hz)
    {
        const double f = clampd (hz, 20.0, fs * os * 0.45);
        const double w = std::tan (kPi * f / (fs * os));
        g = (float) w;
    }
    inline float T (float v) const { return amount < 1e-3f ? v : tanhA (v * amount) / amount; }
    inline float Td (float v) const { return amount < 1e-3f ? 1.f : tanhAd (v * amount); }
    float run1 (float x)
    {
        // input with fixed feedback from the last output (low resonance; one sample of delay is negligible here)
        float u = (x * level + offset) - res * y4;
        for (int i = 0; i < 4; ++i)
        {
            // cell: y = s + g (T(u) - T(y)), T(y) linearised at s -> y = s + g (T(u) - T(s)) / (1 + g T'(s))
            const float tu = T (u), ts = T (s[i]), d = Td (s[i]);
            const float y = s[i] + g * (tu - ts) / (1.f + g * d);
            s[i] = flush (2.f * y - s[i]);
            u = y;
        }
        y4 = u;
        return u / level;
    }
    // x: input sample; cutoffHz: control (may change every sample); returns the output
    float process (float x, float cutoffHz)
    {
        // control feedthrough: fast CV movements (log cutoff) leak to the output
        const float cv = std::log2 (std::fmax (cutoffHz, 20.f));
        if (cvLp < 0.f) cvLp = cv;
        cvLp = cv + (cvLp - cv) * cvLpA;
        const float leak = feed * (cv - cvLp);
        setCutoff (cutoffHz);
        float y;
        if (os == 1) y = run1 (x);
        else if (os == 2) { float a, b; up1.up (x, a, b); const float ya = run1 (a); y = dn1.down (ya, run1 (b)); }
        else
        {
            float a, b, a0, a1, b0, b1;
            up1.up (x, a, b); up2.up (a, a0, a1); up2.up (b, b0, b1);
            const float p0 = run1 (a0), p1 = run1 (a1), p2 = run1 (b0), p3 = run1 (b1);
            y = dn1.down (dn2.down (p0, p1), dn2.down (p2, p3));
        }
        return y * (1.f + res * 0.25f) + leak;                                  // partial passband make-up for res
    }
};
} // namespace sp
