#!/usr/bin/env python3
"""RadioReady EQ: turn presets/factory.json into src/presets.inc (compiled into the plugin).

Each preset lists up to 8 bands (type, freq, gain, q, slope, target), the stereo mode, the QUICK RADIO READY settings
and a note. This script sorts the bands into the 8 slots (low to high), fills unused slots with the Init defaults, and
gain-stages the preset: Output Gain = minus the EQ's average level change on pink-noise-like material
(equal weight per octave, 40 Hz .. 12 kHz), the same estimate the plugin's Auto Gain uses. Bands on the Side only
are left out (a mono-compatible mix carries most of its energy in the Mid). The QUICK section levels itself inside
the plugin, so it is not counted here.
Usage: python3 tools/gen_presets.py   (run from the project folder; `make presets` does it)
"""
import cmath, json, math, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TYPES = ["Peak", "LowShelf", "HighShelf", "HighPass", "LowPass", "Notch", "BandPass"]
SLOPES = {12: 0, 24: 1, 48: 2}
TARGETS = {"Both": 0, "L/Mid": 1, "R/Side": 2}
CATEGORIES = ["Init", "Hip-Hop", "Vocals", "Drums", "Master Bus", "Instruments", "Translation"]
# Init: 1 high-pass (off), 2 low shelf, 3-6 peaks, 7 high shelf, 8 low-pass (off); gain bands are on at 0 dB (transparent)
DEFAULT = [dict(on=0, type="HighPass", freq=30, gain=0, q=0.707, slope=24, target="Both"),
           dict(on=1, type="LowShelf", freq=80, gain=0, q=0.7, slope=24, target="Both"),
           dict(on=1, type="Peak", freq=200, gain=0, q=1.0, slope=24, target="Both"),
           dict(on=1, type="Peak", freq=500, gain=0, q=1.0, slope=24, target="Both"),
           dict(on=1, type="Peak", freq=1500, gain=0, q=1.0, slope=24, target="Both"),
           dict(on=1, type="Peak", freq=4000, gain=0, q=1.0, slope=24, target="Both"),
           dict(on=1, type="HighShelf", freq=10000, gain=0, q=0.7, slope=24, target="Both"),
           dict(on=0, type="LowPass", freq=18000, gain=0, q=0.707, slope=24, target="Both")]
BQ = {1: [0.54119610, 1.30656296], 2: [0.50979558, 0.60134489, 0.89997622, 2.56291545]}

def rbj(t, fs, f, q, g):            # same as src/Biquad.h
    f = min(max(f, 5.0), 0.49 * fs); q = max(q, 0.025)
    w = 2 * math.pi * f / fs; cw, sw = math.cos(w), math.sin(w); A = 10 ** (g / 40); al = sw / (2 * q)
    if t == "Peak": b, a = (1 + al * A, -2 * cw, 1 - al * A), (1 + al / A, -2 * cw, 1 - al / A)
    elif t in ("LowShelf", "HighShelf"):
        s = 2 * math.sqrt(A) * al; k = 1 if t == "LowShelf" else -1
        b = (A * ((A + 1) - k * (A - 1) * cw + s), 2 * k * A * ((A - 1) - k * (A + 1) * cw), A * ((A + 1) - k * (A - 1) * cw - s))
        a = ((A + 1) + k * (A - 1) * cw + s, -2 * k * ((A - 1) + k * (A + 1) * cw), (A + 1) + k * (A - 1) * cw - s)
    elif t == "HighPass": b, a = ((1 + cw) / 2, -(1 + cw), (1 + cw) / 2), (1 + al, -2 * cw, 1 - al)
    elif t == "LowPass": b, a = ((1 - cw) / 2, 1 - cw, (1 - cw) / 2), (1 + al, -2 * cw, 1 - al)
    elif t == "Notch": b, a = (1, -2 * cw, 1), (1 + al, -2 * cw, 1 - al)
    else: b, a = (al, 0, -al), (1 + al, -2 * cw, 1 - al)
    return b, a

def band_db(bd, hz, fs):
    if not bd["on"] or (bd["type"] in ("Peak", "LowShelf", "HighShelf") and abs(bd["gain"]) < 0.001): return 0.0
    cut = bd["type"] in ("HighPass", "LowPass"); sl = SLOPES[bd["slope"]]
    qs = BQ[sl] if cut and sl > 0 else [bd["q"]]
    z = cmath.exp(-2j * math.pi * min(hz, 0.499 * fs) / fs); db = 0.0
    for q in qs:
        b, a = rbj(bd["type"], fs, bd["freq"], q, bd["gain"])
        h = (b[0] + b[1] * z + b[2] * z * z) / (a[0] + a[1] * z + a[2] * z * z)
        db += 20 * math.log10(abs(h) + 1e-12)
    return db

def pink_loudness(bands, fs=48000.0):
    s = 0.0
    for i in range(48):
        hz = 40 * (12000 / 40) ** (i / 47)
        s += 10 ** (sum(band_db(b, hz, fs) for b in bands) / 10)
    return 10 * math.log10(s / 48)

def build():
    data = json.load(open(os.path.join(ROOT, "presets", "factory.json")))
    out = ["// Generated by tools/gen_presets.py from presets/factory.json - edit the JSON, then run `make presets`.",
           "// { name, category, mode (0 Stereo, 1 Mid/Side), {Amount, Low-End, Vocal, Air, Punch} %, output dB,",
           "//   8 x { on, type, freq, gain, q, slope (0 12 / 1 24 / 2 48 dB), target (0 both, 1 L/Mid, 2 R/Side) } }"]
    for p in data["presets"]:
        given = sorted(p["bands"], key=lambda b: b["freq"])
        assert len(given) <= 8, p["name"]
        slots = [dict(d) for d in DEFAULT]
        for i, b in enumerate(given):
            s = dict(on=1, type=b["type"], freq=b["freq"], gain=b.get("gain", 0.0), q=b.get("q", 0.707),
                     slope=b.get("slope", 24), target=b.get("target", "Both"))
            assert s["type"] in TYPES and s["target"] in TARGETS and s["slope"] in SLOPES, p["name"]
            assert 20 <= s["freq"] <= 20000 and -18 <= s["gain"] <= 18 and 0.1 <= s["q"] <= 10, p["name"]
            slots[i] = s
        counted = [s for s in slots if s["target"] != "R/Side"]
        gain = round(max(-12.0, min(12.0, -pink_loudness(counted))), 1) + 0.0
        q = p["quick"]; mode = 1 if p["mode"] == "Mid/Side" else 0
        assert p["category"] in CATEGORIES, p["name"]
        bands = ", ".join("{ %d, %d, %.1ff, %.2ff, %.3ff, %d, %d }" % (s["on"], TYPES.index(s["type"]), s["freq"], s["gain"], s["q"],
                          SLOPES[s["slope"]], TARGETS[s["target"]]) for s in slots)
        out.append('{ "%s", %d, %d, { %g, %g, %g, %g, %g }, %.1ff,\n  { %s } },' % (p["name"], CATEGORIES.index(p["category"]), mode,
                   q["amount"], q["lowEnd"], q["vocal"], q["air"], q["punch"], gain, bands))
    open(os.path.join(ROOT, "src", "presets.inc"), "w").write("\n".join(out) + "\n")
    print(f"wrote src/presets.inc ({len(data['presets'])} presets)")

if __name__ == "__main__":
    build()
